//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG7311_POE_Task_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public decimal Value { get; set; }
        public int Owner { get; set; }
        public byte[] Image { get; set; }
        public string imageContentType { get; set; }
        public string Type { get; set; }
        public System.DateTime DateOfEntry { get; set; }
    
        public virtual User User { get; set; }
    }
}
